# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9717c4afd5628ad02d6666bb51d192d205bcb5faa49ff13f24c922c030ae72475c640d96feadeffd8cdcc7fca651594ebfb572aeb2da424c7e71739e8a26d579

test:
  secret_key_base: a750151b965f948d6915d150bc7ec14c90b069fbd7beb916cc46b030e1c84f0cc4188170760d4256e47db30a27f9fec3d56b1e500bd05a2ffe7bdb282cbd0704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
